name = "AstroImages"
uuid = "fe3fc30c-9b16-11e9-1c73-17dabf39f4ad"
version = "0.6.0"
authors = ["Mosè Giordano", "Rohit Kumar", "William Thompson"]

[workspace]
projects = ["test", "docs"]

[sources]
AstroAngles = {url = "https://github.com/JuliaAstro/AstroAngles.jl"}
DimensionalData = {url = "https://github.com/icweaver/DimensionalData.jl", rev = "makie-0.25"}
FITSFiles = {url = "https://github.com/JuliaAstro/FITSFiles.jl"}
FITSWCS = {url = "https://github.com/JuliaAstro/FITSWCS.jl"}

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
AstroAngles = "5c4adb95-c1fc-4c53-b4ea-2a94080c53d2"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
FITSFiles = "358a0a88-3548-4ad6-b652-8bdbf64af8e5"
FITSWCS = "b9a10f0d-c86c-4e01-8e2e-1f1d7c5fb3f2"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageAxes = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
ImageBase = "c817782e-172a-44cc-b673-b171935fbb9e"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
AstroImagesMakieExt = "Makie"

[compat]
AbstractFFTs = "1.1"
AstroAngles = "0.3"
ColorSchemes = "3.18"
DimensionalData = "0.27, 0.29, 0.30"
FITSFiles = "0.2, 0.3"
FITSWCS = "0.1"
FileIO = "1.15"
ImageAxes = "0.6"
ImageBase = "^0.1.5"
ImageIO = "0.6"
ImageShow = "0.3"
Makie = "0.25"
MappedArrays = "0.4"
PlotUtils = "1.2"
PrecompileTools = "1"
Statistics = "1"
Tables = "1.7"
julia = "1.10"
